### ISSUE TITLE
Add relevant icons to the page

### ISSUE THREAD

**Issue by Sidhegde19** [Sidhegde19/Canteen-System#1]
Relevant icons need to be added to the home page.

**Comment by Gautam-Arora24** [comment]
Can i solve this issue?

**Comment by Jainchhavi16** [comment]
I'd like to contribute too.

**Comment by Malvika18** [comment]
I'd also like to solve this issue.

**Comment by Sidhegde19** [comment]
Please by all means! If you stumble upon errors and potential improvements, then feel free to work on them also.

**Comment by Gautam-Arora24** [comment]
Do we have to add icons to Readme.md file?

**Comment by Sidhegde19** [comment]
Well, the main problem was in the `index.html` page. But if you have improvements in mind for the `README`, that's welcomed too.

P.S: Sorry I am new to these things so I may make some problems by myself

**Comment by munishgarg-02** [comment]
Relevant icons added in index.html file. Please check the pull request.
