### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by Sidhegde19** [Sidhegde19/Canteen-System#3]
Any new and relevant features to the project are welcome!

**Comment by khush31** [comment]
I would like to work on this issue under your mentorship please assign this to me.

**Comment by Sidhegde19** [comment]
I am a newbie myself so I doubt if I can provide mentorship. You are welcome to add features if you want

**Comment by khush31** [comment]
ok, then assign this issue to me

**Comment by khush31** [comment]
ok, then assign this issue to me so that I start working on it.

**Comment by Priyansh-09** [comment]
Hey, I can create Menu Page to this website.  Please assign me this issue !

**Comment by khush31** [comment]
@Sidhegde19 can you give me some images of your canteen and the content of Menu of your canteen.

**Comment by Sidhegde19** [comment]
@khush31 please go ahead and add some of your own selection of pictures. This is a personal project.

**Comment by Sidhegde19** [comment]
> Hey, I can create Menu Page to this website.  Please assign me this issue !

I am sorry as of now only the existing assignees can contribute

**Comment by khush31** [comment]
@Sidhegde19 okk

**Comment by khush31** [comment]
@Sidhegde19  it shows some Fatal error while executing push command
$ git push origin new
remote: Permission to Sidhegde19/Canteen-System.git denied to khush31.
fatal: unable to access 'https://github.com/Sidhegde19/Canteen-System.git/': The requested URL returned error: 403

**Comment by Sidhegde19** [comment]
Well, I suggest you follow this video as the instructions are shown in a simplified manner.

Link: https://youtu.be/c6b6B9oN4Vg

**Comment by khush31** [comment]
ok thanks

**Comment by khush31** [comment]
Hey @Sidhegde19 if my PR is Reviewed then please add the label of hacktoberfest-accepted.
Thank you and It's great working with you

**Comment by Sidhegde19** [comment]
@khush31 rest assured I have done it.  Thank you for your contribution. Great work!
